name: Run Benchmarks

on: workflow_dispatch

jobs:
  prepare-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ID: ${{ env.GITHUB_RUN_ID }}
    outputs:
      issue: ${{ steps.create-issue.outputs.number }}

  benchmark:
    runs-on: ubuntu-latest

    needs: prepare-report

    strategy:
      matrix:
        app: ["vkui", "mui", "yandex"]

    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse CI Action
        id: benchmark
        uses: treosh/lighthouse-ci-action@v7
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ matrix.app }}-$GITHUB_RUN_ID
        with:
          temporaryPublicStorage: true
          configPath: ./lighthouserc
          urls: |
            https://${{ matrix.app }}-benchmark.surge.sh
            https://${{ matrix.app }}-benchmark.surge.sh?mode=modals
            https://${{ matrix.app }}-benchmark.surge.sh?mode=burn
      - name: add results to report
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "
          ## ${{matrix.app}}-benchmark:

          ```json
          ${{ steps.benchmark.outputs.links }}
          ```
          "
          issue_number: ${{ needs.prepare-report.outputs.issue }}
          token: ${{ secrets.GITHUB_TOKEN }}
        
