name: Run Benchmarks

on: workflow_dispatch

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ["vkui", "mui", "yandex"]

    steps:
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v7
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ matrix.app }}-$GITHUB_RUN_ID
        with:
          temporaryPublicStorage: true
          configPath: ./lighthouserc.js
          urls: |
            https://${{ matrix.app }}-benchmark.surge.sh
            https://${{ matrix.app }}-benchmark.surge.sh?mode=modals
            https://${{ matrix.app }}-benchmark.surge.sh?mode=burn
