name: Run Benchmarks

on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  benchmark:
    runs-on: ubuntu-latest

    needs: report

    strategy:
      matrix:
        app: ["vkui", "mui", "yandex"]

    steps:
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v7
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ matrix.app }}-$GITHUB_RUN_ID
        with:
          temporaryPublicStorage: true
          configPath: ./lighthouserc
          urls: |
            https://${{ matrix.app }}-benchmark.surge.sh
            https://${{ matrix.app }}-benchmark.surge.sh?mode=modals
            https://${{ matrix.app }}-benchmark.surge.sh?mode=burn
        
