name: Build and Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app: ["vkui", "mui", "yandex", "f7", "spectrum", "lightning"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: yarn
      - run: npx lerna bootstrap --scope @vkui-benchmarks/${{ matrix.app }}-benchmark
      - run: yarn build:${{ matrix.app }}
      - name: deploy to surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npx surge ./apps/${{ matrix.app }}-benchmark/build ${{ matrix.app }}-benchmark.surge.sh
