# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run Benchmarks

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app: ["vkui"] #, "mui", "yandex"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: yarn
      - run: npx lerna bootstrap --scope @vkui-benchmarks/${{ matrix.app }}-benchmark
      - run: yarn build:${{ matrix.app }}
      - name: deploy to surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npx surge ./apps/${{ matrix.app }}-benchmark/build ${{ matrix.app }}-benchmark.surge.sh
        

  # benchmark:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #     - name: Lighthouse CI Action
  #       # You may pin to the exact commit or the version.
  #       # uses: treosh/lighthouse-ci-action@05136f54163d97b090a570852739b442754d8237
  #       uses: treosh/lighthouse-ci-action@v7
  #       with:
  #         # List of URL(s) to analyze
  #         urls:
  #           test
