# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run Benchmarks

on: workflow_dispatch

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app: ["vkui-benchmark", "mui-benchmark", "yandex-benchmark"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: yarn
      - run: npx lerna bootstrap --scope @vkui-benchmarks/${{ matrix.app }}
      - run: yarn build:${{ matrix.app }}


